apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: cruise
  annotations:
    cruise.etna/project: "isr-orc4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        app.kubernetes.io/name: backend
        app.kubernetes.io/part-of: cruise
    spec:
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: backend
        image: 192.168.56.25:30500/backend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: backend-config