apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: cruise
  MYSQL_USER: cruise
  MYSQL_PASSWORD: cruisepass