# Secret — Identifiants sensibles de la base de données
# Les valeurs sont encodées en base64

# Pour encoder en base64 :
# echo -n "todouser" | base64     → dG9kb3VzZXI=
# echo -n "todopassword" | base64 → dG9kb3Bhc3N3b3Jk
# echo -n "rootpassword" | base64 → cm9vdHBhc3N3b3Jk

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: prod
  labels:
    app: mysql
    env: prod
    project: cruise
type: Opaque
data:
  DB_USER: dG9kb3VzZXI=
  DB_PASSWORD: dG9kb3Bhc3N3b3Jk
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
