apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: cruise
  annotations:
    cruise.etna/project: "isr-orc4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: cruise
    spec:
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: frontend
        image: 192.168.56.25:30500/frontend:v2
        ports:
        - containerPort: 80