all:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ~/.ssh/vagrant_key
    ansible_python_interpreter: /usr/bin/python3
    
  children:
    masters:
      hosts:
        master:
          ansible_host: 192.168.56.25
          node_type: master
          
    workers:
      hosts:
        worker1:
          ansible_host: 192.168.56.26
          node_type: worker
        worker2:
          ansible_host: 192.168.56.27
          node_type: worker
          
    all_nodes:
      children:
        - masters
        - workers
        
    kubernetes_cluster:
      children:
        - all_nodes
