[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/.ssh/vagrant_key
ansible_python_interpreter=/usr/bin/python3

[masters]
master ansible_host=192.168.56.25

[workers]
worker1 ansible_host=192.168.56.26
worker2 ansible_host=192.168.56.27

[all_nodes:children]
masters
workers

[kubernetes_cluster:children]
all_nodes
